require_relative '../author'
require_relative '../game'
require_relative '../label'
require_relative '../item'
require_relative '../book'
require_relative '../main_methods/book_main.rb'
require_relative '../main_methods/label_main.rb'
require_relative '../main_methods/game_main.rb'
require_relative '../main_methods/author_main.rb'

require 'yaml'
