require_relative '../author'
require_relative '../game'
require_relative '../label'
require_relative '../item'
require_relative '../book'
require_relative '../music'
require_relative '../gener'
require_relative '../main_methods/book_main'
require_relative '../main_methods/label_main'
require_relative '../main_methods/game_main'
require_relative '../main_methods/author_main'
require_relative '../main_methods/music_main.rb'
require_relative '../main_methods/main_genre.rb'

require 'yaml'
